reset:
  countdown-seconds: 10

scoreboard:
  enabled: true
  update-interval-ticks: 20

worlds:
  # Permanent safety/fallback world.
  # This should match the normal Paper level-name.
  lobby-world: world

  # Radius around active/standby Overworld spawn to generate ahead of time.
  #
  # 0 = 1 chunk
  # 1 = 3x3 chunks
  # 2 = 5x5 chunks
  preload-radius-chunks: 1